device:
  wss1:
    com_power: "COM5"
    com_control: "COM6"
    list_att_initial:
      - # device 1 (MUX): com_port 1, 2 各自的 20 个 switch_port 衰减补偿
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - # device 2 (DEMUX)
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  wss2:
    com_power: "COM7"
    com_control: "COM8"
    list_att_initial:
      - # device 1 (MUX)
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - # device 2 (DEMUX)
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  tls:
    mtp_ip: "192.168.1.102"
    iqs_ip: "192.168.1.101"

  osa:
    ip: "192.168.1.113"
    port: 10001

  qkd:
    ip: "192.168.1.20"
    port: 56100
    username: "qkd"
    password: "qasky1234"
    log_file_path: "log"
    log_file_name: "qkd.alice-bob.log.0"

  ase:
    port: "COM6"
    baud: 9600
    target_power_mw: 100

  sfp:
    transport: "serial"
    serial_port: "COM3"
    baudrate: 115200

  wss_port:
    quantum: 2
    real_source: 4
    ase_source: 6
    wdm_classical: 8

experiment:
  distance: 10000        # m
  max_power: 13          # dBm
  actual_power: 13       # dBm
  inv_time: 2400         # s
  wait_time: 600         # s
  fq: 193.5e+12          # Hz
  fsyn: 193.3e+12        # Hz
  spacing: 100.0e+9      # Hz
  num_c: 8
  raman_file: "simulation/Ramancrosssection25GHz（25GHz间隔）.xls"
  repetition: 1          # 实验重复次数
  spacing_list:
    - 100000000000        # 信道间隔列表 (Hz)
  scheme_name_list:      # 实验方案名称列表
    - "interleave"
    - "CCA"
    - "max_SKR"
    - "stable_SKR"
  light_source:
    type: "TLS"              # TLS | SFP | OTN
    tls_bandwidth: 20.0e+9   # Hz
    sfp_bandwidth: 20.0e+9   # Hz (OSA光谱图实测99%功率带宽)
    otn_bandwidth: 45.0e+9   # Hz (OSA光谱图实测99%功率带宽)
    tls_max_count: 8
    sfp_max_count: 1
    otn_max_count: 1
