device:
  wss1:
    com_power: "COM5"
    com_control: "COM6"
    list_att_initial:
      - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  wss2:
    com_power: "COM7"
    com_control: "COM8"
    list_att_initial:
      - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  tls:
    mtp_ip: "192.168.1.102"
    iqs_ip: "192.168.1.101"

  osa:
    ip: "192.168.1.113"
    port: 10001

  qkd:
    ip: "192.168.1.20"
    port: 56100
    username: "qkd"
    password: "qasky1234"
    log_file_path: "log"
    log_file_name: "qkd.alice-bob.log.0"

  ase:
    port: "COM6"
    baud: 9600
    target_power_mw: 100

experiment:
  distance: 10000        # m
  max_power: 13          # dBm
  actual_power: 13       # dBm
  buffer_time: 600       # s
  inv_time: 2400         # s
  wait_time: 600         # s
  fq: 193.5e12           # Hz
  fsyn: 193.3e12         # Hz
  spacing: 100e9         # Hz
  num_c: 8
  raman_file: "simulation/Ramancrosssection25GHz（25GHz间隔）.xls"
  repetition: 1          # 实验重复次数
  spacing_list:
    - 100000000000        # 信道间隔列表 (Hz)
  scheme_name_list:      # 实验方案名称列表
    - "interleave"
    - "CCA"
    - "max_SKR"
    - "stable_SKR"
